services:
  frontend:
    build: ./frontend
    container_name: quizapp-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - quizapp-network

  backend:
    build: ./backend
    container_name: quizapp-backend
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    restart: unless-stopped
    networks:
      - quizapp-network

networks:
  quizapp-network:
    driver: bridge 