version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: quizapp-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - quizapp-network

  backend:
    build: ./backend
    container_name: quizapp-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/quizapp
      - GIN_MODE=release
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - quizapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:7
    container_name: quizapp-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=quizapp
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - quizapp-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/quizapp --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo_data:
    driver: local

networks:
  quizapp-network:
    driver: bridge 